import Foundation
import StarlingCore

enum AdversarialFixtures {
    static let now = Date(timeIntervalSince1970: 1_790_967_600)
    static let alice = try! PeerID(hex: String(repeating: "aa", count: 32))
    static let bob = try! PeerID(hex: String(repeating: "bb", count: 32))
    static let conversation = ConversationID(UUID(uuidString: "00000000-0000-4000-8000-000000000001")!)
    static let message = MessageID(UUID(uuidString: "00000000-0000-4000-8000-000000000002")!)

    // Copied from Core's frozen v0 golden frame, not generated by the codec under test.
    static let golden = #"{"body":{"type":"propose","value":{"round":0,"terms":{"activity":{"keywords":["food"],"type":"keywords"},"budget":{"amount":{"currency":"USD","minor":1500},"type":"amount"},"time":{"slots":[{"end":29849640,"start":29849460}],"type":"slots"}}}},"conversation":"00000000-0000-4000-8000-000000000001","id":"00000000-0000-4000-8000-000000000002","recipient":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","sender":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","sentAt":1790967600000,"sequence":0,"version":0}"#

    static func body(_ kind: MessageBody.Kind) throws -> MessageBody {
        let terms = try Terms([.activity: .keywords([try Keyword("food")]), .budget: .amount(try MoneyAmount(minorUnits: 1500))])
        let proposal = try Proposal(round: 0, terms: terms)
        switch kind {
        case .hello: return .hello(try AgentCard(model: .onDevice, capabilities: [.down, .psi]))
        case .propose: return .propose(proposal)
        case .counter: return .counter(proposal)
        case .accept: return .accept(Acceptance(proposal: message, terms: terms))
        case .reject: return .reject(Rejection(proposal: message, reason: .noOverlap))
        case .query: return .query(try Query(issue: .activity, candidates: .keywords([try Keyword("food")])))
        case .answer: return .answer(try Answer(query: message, issue: .activity, status: .answered, acceptable: .keywords([try Keyword("food")])))
        case .psi: return .psi(try PSIFrame(session: conversation.rawValue, step: 0, payload: Data([0, 1, 255])))
        }
    }

    static func envelope(_ body: MessageBody) throws -> Envelope {
        try Envelope(id: message, conversation: conversation, sender: alice, recipient: bob,
                     sequence: 0, sentAt: Timestamp(now), body: body)
    }
}

/// SplitMix64 with explicit modulo selection keeps the mutation stream stable
/// across Swift standard library versions.
struct MutationGenerator {
    var state: UInt64

    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var value = state
        value = (value ^ (value >> 30)) &* 0xBF58_476D_1CE4_E5B9
        value = (value ^ (value >> 27)) &* 0x94D0_49BB_1331_11EB
        return value ^ (value >> 31)
    }

    mutating func index(_ count: Int) -> Int { Int(next() % UInt64(count)) }
}
